name: terabox

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Requirements 
        run: |
          git clone https://github.com/Hrishi2861/Terabox-Downloader-Bot/
          cd Terabox-Downloader-Bot && rm config.env && cd .. && cp config.env Terabox-Downloader-Bot/ && cd Terabox-Downloader-Bot 
          sudo docker build . -t terabox
      - name: Run Script
        run: |
            sudo docker run -p 80:80 -p 8080:8080 terabox
